services:
  postgres:
    image: postgres:latest
    container_name: gerenciamento-turmas-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-networks

  backend:
    build: ./backend
    container_name: gerenciamento-turmas-backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CORS_ORIGIN=http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run prisma:generate && npm run prisma:migrate && npm run dev"
    networks:
      - app-networks
    restart: always

  frontend:
    build: ./frontend
    container_name: gerenciamento-turmas-frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-networks
    restart: always

networks:
  app-networks:
    driver: bridge

volumes:
  postgres_data:
  
